from __future__ import annotations

# E3.1 Real Code Generation Engine
from runtime.contracts.generators import (
    BlockingConflict,
    BlockingConflictReport,
    BlockingConflictDetector,
    CodeGenerationError,
    ContentValidationCheck,
    ContentValidationError,
    ContentValidationResult,
    ContentValidator,
    GeneratedContent,
    GenerationContext,
    GenerationContextBuilder,
    GenerationContextError,
    GenerationReport,
    GenerationRequest,
    GenerationRequestConstructor,
    GenerationResult,
    OutputNormalizer,
    PatternLibrary,
    PatternResolver,
    PatternResolution,
    PatternResolutionError,
    RealCodeGenerationEngine,
    RepositoryWriter,
    RepositoryWriteError,
    RepositoryWriteResult,
    TemplateResolver,
    TemplateResolution,
    TemplateResolutionError,
    WaveGenerationResult,
    create_generated_content,
    get_invocation_engine,
    set_invocation_engine,
)
# E2.1 builder
from runtime.contracts.builder import EngineeringContractBuilder
from runtime.contracts.e21_models import (
    ACCEPTANCE_CRITERIA_TEMPLATES,
    DELIVERABLE_VERIFICATION_METHOD,
    DISCIPLINE_DELIVERABLE_TYPE,
    DISCIPLINE_REPOSITORY_SCOPE,
    PRIORITY_RANK,
    SKILL_PRIORITY_TO_GENERATION,
    AcceptanceCriteria,
    ContractCoverageMetrics,
    ContractTraceability,
    DeliverableContract,
)
# E2.2 decomposition
from runtime.contracts.decomposition import (
    ACCEPTANCE_CRITERIA_TEMPLATES as E22_AC_TEMPLATES,
    ArtifactRoute,
    CONTRACT_DECOMPOSITION_RULES,
    CONTRACT_DELIVERABLE_TYPE,
    CONTRACT_REPOSITORY_SCOPE,
    CONTRACT_VERIFICATION_METHOD,
    ContractDecompositionError,
    ContractDecompositionReport,
    ContractDecompositionValidator,
    DependencyEdge,
    DependencyGraph,
    DependencyType,
    DecompositionCoverageMetrics,
    DeterminismError,
    DuplicateIDError,
    ExecutionWave,
    ParallelExecutionGroup,
    SubContract,
    TechnologyMismatchError,
    TraceabilityError,
    ValidationError,
    WaveOrderingError,
)
from runtime.contracts.decomposer import ContractDecompositionEngine
# E2.3 artifact execution planning
from runtime.contracts.e23_models import (
    ArtifactDependencyGraph,
    ArtifactDependencyEdge,
    ArtifactDependencyType,
    ArtifactDependencyInput,
    ArtifactExecutionPlan,
    ArtifactExecutionUnit,
    ArtifactExecutionWave,
    ArtifactExecutionOrder,
    ArtifactPlanningError,
    ConflictReport,
    GenerationStrategy,
    GenerationStrategySummary,
    PathResolutionError,
    PathType,
    RepositoryBoundary,
    RepositoryScopeSummary,
    StrategyUnresolvedError,
    ValidationCategory,
    ValidationCheckpoint,
    OverwritePolicy,
    ConflictType,
    Conflict,
    compute_artifact_execution_id,
    compute_artifact_execution_hash,
    compute_plan_hash,
    normalize_path,
    validate_absolute_path,
    validate_no_traversal,
)
from runtime.contracts.planner import ArtifactExecutionPlanner
# P4.G4 engine
from runtime.contracts.engine import DISCIPLINE_WAVE_MAP, EngineeringContractEngine
# P4.G4 models
from runtime.contracts.exceptions import (
    ContractConstraintError,
    ContractCoverageError,
    ContractDependencyError,
    ContractValidationError,
    EngineeringContractError,
)
from runtime.contracts.models import EngineeringContract, EngineeringContractReport
from runtime.contracts.validation import ContractValidator
# E3.4 Repository & Workspace Integration
from runtime.contracts.e34_models import (
    ArtifactFileResult,
    ExecutionError,
    InvalidMissionError,
    InvalidPlanError,
    MissionRequirements,
    ProjectExecutionResult,
    ProjectInitializer,
    ProjectType,
    WorkspaceBoundaryError,
    WorkspaceResolution,
    WorkspaceResolutionError,
    compute_execution_result_hash,
)
from runtime.contracts.integration import (
    MissionRequirementsAdapter,
    MissionToPlanConverter,
    ProjectExecutionEngine,
    ProjectGenerator,
    WorkspaceResolver,
)

__all__ = [
    # P4.G4 core
    "EngineeringContractEngine",
    "EngineeringContractReport",
    "EngineeringContract",
    "DISCIPLINE_WAVE_MAP",
    "EngineeringContractError",
    "ContractValidationError",
    "ContractConstraintError",
    # E2.1 builder
    "EngineeringContractBuilder",
    # E2.1 validator
    "ContractValidator",
    # E2.1 extended models
    "ContractCoverageMetrics",
    "ContractCoverageError",
    "ContractDependencyError",
    "DeliverableContract",
    "AcceptanceCriteria",
    "ContractTraceability",
    # E2.2 decomposition
    "ContractDecompositionEngine",
    "ContractDecompositionReport",
    "SubContract",
    "DependencyGraph",
    "DependencyEdge",
    "DependencyType",
    "ArtifactRoute",
    "ExecutionWave",
    "ParallelExecutionGroup",
    "DecompositionCoverageMetrics",
    "ContractDecompositionValidator",
    "ContractDecompositionError",
    "ValidationError",
    "DeterminismError",
    "DuplicateIDError",
    "TechnologyMismatchError",
    "TraceabilityError",
    "WaveOrderingError",
    # E2.3 artifact execution planning
    "ArtifactExecutionPlanner",
    "ArtifactExecutionPlan",
    "ArtifactExecutionUnit",
    "ArtifactExecutionWave",
    "ArtifactExecutionOrder",
    "ArtifactDependencyGraph",
    "ArtifactDependencyEdge",
    "ArtifactDependencyType",
    "ArtifactDependencyInput",
    "GenerationStrategy",
    "GenerationStrategySummary",
    "PathType",
    "OverwritePolicy",
    "ValidationCategory",
    "ValidationCheckpoint",
    "RepositoryBoundary",
    "RepositoryScopeSummary",
    "ConflictType",
    "Conflict",
    "ConflictReport",
    "ArtifactPlanningError",
    "PathResolutionError",
    "StrategyUnresolvedError",
    # E3.1 Real Code Generation Engine
    "RealCodeGenerationEngine",
    "GenerationContext",
    "GenerationContextBuilder",
    "GenerationContextError",
    "GenerationRequest",
    "GenerationRequestConstructor",
    "GeneratedContent",
    "GenerationResult",
    "GenerationReport",
    "WaveGenerationResult",
    "TemplateResolver",
    "TemplateResolution",
    "TemplateResolutionError",
    "PatternResolver",
    "PatternLibrary",
    "PatternResolution",
    "PatternResolutionError",
    "OutputNormalizer",
    "ContentValidator",
    "ContentValidationResult",
    "ContentValidationCheck",
    "ContentValidationError",
    "RepositoryWriter",
    "RepositoryWriteResult",
    "RepositoryWriteError",
    "BlockingConflictDetector",
    "BlockingConflictReport",
    "BlockingConflict",
    "CodeGenerationError",
    "create_generated_content",
    "get_invocation_engine",
    "set_invocation_engine",
    # E3.4 Repository & Workspace Integration
    "MissionRequirements",
    "ProjectExecutionResult",
    "ProjectInitializer",
    "ProjectType",
    "WorkspaceResolution",
    "WorkspaceBoundaryError",
    "WorkspaceResolutionError",
    "InvalidMissionError",
    "InvalidPlanError",
    "ExecutionError",
    "ArtifactFileResult",
    "compute_execution_result_hash",
    "MissionRequirementsAdapter",
    "MissionToPlanConverter",
    "ProjectExecutionEngine",
    "ProjectGenerator",
    "WorkspaceResolver",
    # Helpers
    "compute_artifact_execution_id",
    "compute_artifact_execution_hash",
    "compute_plan_hash",
    "normalize_path",
    "validate_absolute_path",
    "validate_no_traversal",
    # Discipline mappings
    "DISCIPLINE_REPOSITORY_SCOPE",
    "DISCIPLINE_DELIVERABLE_TYPE",
    "DELIVERABLE_VERIFICATION_METHOD",
    "ACCEPTANCE_CRITERIA_TEMPLATES",
    "SKILL_PRIORITY_TO_GENERATION",
    "PRIORITY_RANK",
    # E2.2 mappings
    "CONTRACT_REPOSITORY_SCOPE",
    "CONTRACT_DELIVERABLE_TYPE",
    "CONTRACT_VERIFICATION_METHOD",
    "CONTRACT_DECOMPOSITION_RULES",
]
